### ISSUE TITLE
Onboarding Page - Use existing google doc

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#292]
Putting this on the backlog. Didn't know there was so much information on how to onboard. Will recommend using github wiki setup to create the sections.

https://www.notion.so/product?utm_source=google&utm_campaign=2075789710&utm_medium=80211061601&utm_content=500427479647&utm_term=notion&targetid=kwd-312974742&gclid=Cj0KCQjwy5maBhDdARIsAMxrkw0PZGXfK5DC8ag4VGp6ZaptO93NYlGn5MWkN2hlOXKKev0AcsxozCQaAutoEALw_wcB

Onboarding Google Doc - https://docs.google.com/document/d/1L5Hc8_K_NhVhAejdE05C_Y__CgqeBWFrFYFoNqBSBbQ/edit

**Comment by ri0nardo** [comment]
@Tijani-zainab can we close this as the current way onboarding is works well enough.

**Comment by Tijani-zainab** [comment]
@ri0nardo I worked on it already, didn't realize I did not link the PR to the issue.
will do so now, and you can  review

**Comment by Tijani-zainab** [comment]
Oh, my mistake
I confused this Issue with #112 issue, for adding **PR template**
yeah, I think we should go ahead and close it. the current onboarding docs works fine @ri0nardo
