### ISSUE TITLE
Fix all eslint issues (auto-fixable)

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_front#302]
Run `npm run lint:fix` to fix the issues that can be auto-fixed.

**Comment by jazhen** [comment]
@Tijani-zainab - I made some config change on a branch: [302-fix-all-eslint-issues-auto-fixable](https://github.com/waterthetrees/wtt_front/tree/302-fix-all-eslint-issues-auto-fixable).

Do you want to run the command in the description and I can review?

**Comment by Tijani-zainab** [comment]
Oh Okay then I'd do that, will make the commit soon and send the pr
@jazhen
