### ISSUE TITLE
Implement Halloween Logo to Site

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#306]
Implement the New Halloween Logo to the Live Site. If possible set a end date to the Logo to go back to the original logo on November 3 since that's the end of the day of the dead. This is an svg file

![Image](https://user-images.githubusercontent.com/98299952/195507724-9d9e6226-5ced-4d99-b11f-60be50018c13.svg)

wtt_front #296

**Comment by ri0nardo** [comment]
@Tijani-zainab will have the favicon files uploaded in a few hours. Look out for another issue for the favicon

**Comment by Tijani-zainab** [comment]
Hi Randy 👋🏾 @ri0nardo 
can I also get a png for the Halloween logo please

Thank you !

**Comment by Tijani-zainab** [comment]
Hiii again @ri0nardo 
sorry, never mind about the png 

implemented the svg already
