### ISSUE TITLE
Implement Christmas Favicon to Site

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#307]
Implement the New Christmas Favicon to the Live Site. Start the new Favicon on November 3rd when we switch from Halloween to Christmas. If there is a timer feature end the Christmas favicon on December 31.

https://www.wix.com/blog/2019/07/what-is-favicon-how-to-make/#:~:text=The%20original%20favicon%20format%20was,GIF%20favicons%20harder%20to%20see.

I found an article stating that an SVG favicon is the future. Not sure what the format of the current favicon is, but I am including both an SVG and PNG. SVG is preferred.

wtt_front #296

**Comment by ri0nardo** [comment]
SVG Files

Sizing is 16 pixels, 32 pixels, and 96 pixels

![Image](https://user-images.githubusercontent.com/98299952/195517538-a7610f92-2bbc-416a-ad36-b431547a403b.svg)
![Image](https://user-images.githubusercontent.com/98299952/195517536-e0bc5c09-cf77-43d0-a0c5-5cce71d38dee.svg)
![Image](https://user-images.githubusercontent.com/98299952/195517537-6c2f936d-9d7e-4f19-9722-933d9ccab5d2.svg)

**Comment by ri0nardo** [comment]
PNG Files

Sizing is 16 pixels, 32 pixels, and 96 pixels



![Image](https://user-images.githubusercontent.com/98299952/195517677-96389e42-d45d-4729-a3bb-51e4e86aadb3.png)
![Image](https://user-images.githubusercontent.com/98299952/195517676-760e1c98-7db8-4943-8794-14a5049c7bdc.png)
![Image](https://user-images.githubusercontent.com/98299952/195517678-ef61496e-4533-4a9e-b029-0b5bd2ca363c.png)

**Comment by ri0nardo** [comment]
@Tijani-zainab we can start changing the favicon on the main site. Whenever you are ready

**Comment by ri0nardo** [comment]
@Tijani-zainab adding the new logo


![Image](https://user-images.githubusercontent.com/98299952/204962866-15fcf3fd-064b-45bc-a525-1e7bf97c4f6c.png)
![Image](https://user-images.githubusercontent.com/98299952/204962865-579133bc-9f26-4eb3-be17-dcccaf40e803.svg)

**Comment by Tijani-zainab** [comment]
will get on it now !
