### ISSUE TITLE
Implement Christmas Logo to Site

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#309]
Implement the New Christmas Logo to the Live Site. If possible set a start and end date to the Logo to go back to the original logo starting November 3rd to December 31st.

Logo in progress.

Will have two versions of Logo.
Desktop
H: 24 Pixels
W: 216 Pixels

Mobile
H: 16 pixels
W:  144 Pixels

wtt_front #296

**Comment by M1racle04** [comment]
Hii , i would like to work on this

**Comment by ri0nardo** [comment]
@M1racle04 sorry but Tijani is already assigned to this ticket.

**Comment by Tijani-zainab** [comment]
Hi Randy 👋🏾 @ri0nardo 
Good day
please could you upload the pictures for the logo to this issue please ? 
or are they still work in progress ?

Thank You !

**Comment by Tijani-zainab** [comment]
found the logo !
sorry to bother you @ri0nardo
