### ISSUE TITLE
Issue with no scrolling on Privacy Police Page

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#315]
Link to privacy page - https://waterthetrees.com/privacy

The privacy policy page has an issue where the info below isn't accessible to certain screen sizes. I am attaching a photo of the issue from my laptop. If you zoom out you can see all the context, but not everyone can figure that out.

Issue:
- Figure out why the page is not scrolling on certain screen sizes.

![Image](https://user-images.githubusercontent.com/98299952/196061636-f9332a58-f1e8-4d0b-936b-e572e1352c12.png)

![Image](https://user-images.githubusercontent.com/98299952/196061641-5202825c-fab6-45f5-a41d-7b092030d617.png)

**Comment by jazhen** [comment]
Similar issue for about, contact, license, and user profile pages. Start with the privacy page and look into the others to see if it's the same issue. If not, we can create separate issues for the other pages.

**Comment by chinmaykumbhare** [comment]
hi @jazhen @ri0nardo I can fix it. Can you please assign this issue to me?

**Comment by jazhen** [comment]
@chinmaykumbhare - Assigned. We found that the changes probably will affect other pages, so you will need to do some regression testing on other pages.

**Comment by ri0nardo** [comment]
@chinmaykumbhare how is progress on this ticket?
