### ISSUE TITLE
Issue with no scrolling on License Page

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#316]
Link to license page - https://waterthetrees.com/license

The license page has an issue where the info below isn't accessible to certain screen sizes. I am attaching a photo of the issue from my laptop. If you zoom out you can see all the context, but not everyone can figure that out.

Issue:

Figure out why the page is not scrolling on certain screen sizes.

See issue #270 

![Image](https://user-images.githubusercontent.com/98299952/196061705-9d88f703-35f8-4401-bbc0-2d85c073cc77.png)
![Image](https://user-images.githubusercontent.com/98299952/196061704-6e382236-853a-44fe-8ec1-4bb2d6e7a91f.png)

**Comment by byfar94** [comment]
Please assign it to me

**Comment by CalArcher** [comment]
Can you assign this to me?

**Comment by pratyushkr11** [comment]
Hello @ri0nardo I would like to work on this issue. Can you assign this to me

**Comment by ri0nardo** [comment]
@pratyushkr11 have you made progress on this ticket?
