### ISSUE TITLE
Blog Page - Develop the Water the Trees Blog

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#329]
Discovered Water the Trees Blog. No content is available, but a topic to tackle eventually.

Link - blog.waterthetrees.com

**Comment by DamyanBG** [comment]
I can start with the blog too.

**Comment by DamyanBG** [comment]
I am happy that you assigned the task to me. So, where to find this the source for this blog ? Do I need some credentials ?

**Comment by ri0nardo** [comment]
I am not sure where the source is. I was recently informed that there was a blog.

**Comment by DamyanBG** [comment]
I wrote in the Slack chat to ask where is the source.

**Comment by DamyanBG** [comment]
OK, I am waiting for news.

**Comment by DamyanBG** [comment]
@jazhen Any updates about this ?

**Comment by DamyanBG** [comment]
I will unassigned myself, because of no info.

**Comment by ri0nardo** [comment]
@DamyanBG there aren't any plans to continue the blog right now. We have a linkedin group that can be used as a substitute for the blog.
