### ISSUE TITLE
Fix ESLint issues (Errors) - react/jsx-key

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_front#335]
> Running `npm run lint` in the command line shows various ESLint issues that we should fix. The issues are split into warnings (yellow-coded) and errors (red-coded). Within warnings and errors, the issues are split into categories by ESLint rule name.
> 
> Example: ![image](https://user-images.githubusercontent.com/6326660/197923380-4c777e9b-8a8b-461b-8839-cde324be0a72.png)

Fix all errors under the category `react/jsx-key`. _Please make sure to regression test so that we know nothing has broken through these changes._

List of issues (May not be exhaustive so double check):

- [ ] `wtt_front/client/src/pages/NewTree/NewTreeAddress.js`
  - [ ]   16:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   17:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   18:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   19:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   20:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   21:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   22:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   23:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   24:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   25:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   26:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   27:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   28:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   29:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   30:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   31:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   32:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   33:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   34:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   35:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   36:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   37:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   38:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   39:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   40:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   41:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   42:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   43:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   44:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   45:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   46:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   47:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   48:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   49:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   50:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   51:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   52:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   53:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   54:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   55:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   56:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   57:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   58:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   59:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   60:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   61:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   62:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   63:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   64:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   65:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   66:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   67:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   68:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   69:3  error  Missing "key" prop for element in array  react/jsx-key
  - [ ]   70:3  error  Missing "key" prop for element in array  react/jsx-key

**Comment by trishnakalita660** [comment]
@jazhen  Can you assign this to me?

**Comment by jazhen** [comment]
> @jazhen  Can you assign this to me?
> 

Assigned. Thank you!
