### ISSUE TITLE
Fix ESLint issues (Errors) - no-unused-vars

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_front#336]
> Running `npm run lint` in the command line shows various ESLint issues that we should fix. The issues are split into warnings (yellow-coded) and errors (red-coded). Within warnings and errors, the issues are split into categories by ESLint rule name.
> 
> Example: ![image](https://user-images.githubusercontent.com/6326660/197923380-4c777e9b-8a8b-461b-8839-cde324be0a72.png)

Fix all errors under the category `no-unused-vars`. _Please make sure to regression test so that we know nothing has broken through these changes._

List of issues (May not be exhaustive so double check):

- [x] `wtt_front/client/src/pages/Map/MapboxControlPortal.js`
  - [x]    1:8  error    'React' is defined but never used                                                                                              no-unused-vars
- [x] `wtt_front/client/src/pages/Map/MapboxMarkerPortal.js`
  - [x]    1:8  error    'React' is defined but never used                                                                                                                      no-unused-vars
- [x] `wtt_front/client/src/pages/NewTree/NewTreePlantingMarker.js`
  - [x]    3:10  error    'TooltipBottom' is defined but never used                                                                                                        no-unused-vars
  - [x]    8:8   error    'NewTreeOpenAddButton' is defined but never used                                                                                                 no-unused-vars
  - [x]   23:7   error    'Toolbar' is assigned a value but never used                                                                                                     no-unused-vars
- [x] `wtt_front/client/src/pages/NewTree/NewTreePlantingTarget.js`
  - [x]    4:10  error  'NewTreeCrosshairs' is defined but never used  no-unused-vars
- [x] `wtt_front/client/src/pages/Privacy/Privacy.js`
  - [x]   4:18  error  'props' is defined but never used  no-unused-vars
- [x] `wtt_front/client/src/pages/Tree/AdoptLikeCheckboxes.js`
  - [x]    3:21  error  'Link' is defined but never used                  no-unused-vars
  - [x]   20:10  error  'useDebouncedCallback' is defined but never used  no-unused-vars
  - [x]   83:3   error  'edit' is defined but never used                  no-unused-vars
- [x] `wtt_front/client/src/pages/Tree/TreeHeader.js`
  - [x]   3:8   error  'format' is defined but never used  no-unused-vars
  - [x]   6:10  error  'styled' is defined but never used  no-unused-vars
- [x] `wtt_front/client/src/pages/Tree/TreeNotes.js`
  - [x]    5:3  error    'useTreeQuery' is defined but never used                                                                                                                                                                                              no-unused-vars
- [x] `wtt_front/server/logger.js`
  - [x]   115:18  error  'encoding' is defined but never used  no-unused-vars

**Comment by DamyanBG** [comment]
Please, assign me the issue.

**Comment by jazhen** [comment]
> Please, assign me the issue.

Assigned. Thank you!

**Comment by jazhen** [comment]
Closed by #352
