### ISSUE TITLE
Fix ESLint issues (Errors) - no-prototype-builtins

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_front#338]
> Running `npm run lint` in the command line shows various ESLint issues that we should fix. The issues are split into warnings (yellow-coded) and errors (red-coded). Within warnings and errors, the issues are split into categories by ESLint rule name.
> 
> Example: ![image](https://user-images.githubusercontent.com/6326660/197923380-4c777e9b-8a8b-461b-8839-cde324be0a72.png)

Fix all errors under the category `no-prototype-builtins`. _Please make sure to regression test so that we know nothing has broken through these changes._

List of issues (May not be exhaustive so double check):

- [ ] `wtt_front/client/src/pages/Tree/Tree.js`
  - [ ]   75:33  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins

**Comment by anup-a** [comment]
Can I take a stab at this one ?

**Comment by jazhen** [comment]
@anup-a - I assigned you to https://github.com/waterthetrees/wtt_front/issues/340 yesterday. How is this going?

**Comment by anup-a** [comment]
That is a different person. However I was working on this https://github.com/waterthetrees/wtt_front/pull/343? Can you check if that one is okay?

**Comment by jazhen** [comment]
@anup-a - I'll request a re-review for #343 and you can start on this one then. Assigned.

**Comment by anup-a** [comment]
I have the required changes with me on local, waiting for the previous one to get merged, before creating another PR.
