### ISSUE TITLE
Fix ESLint issues (Errors) - jsx-a11y/alt-text

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_front#340]
> Running `npm run lint` in the command line shows various ESLint issues that we should fix. The issues are split into warnings (yellow-coded) and errors (red-coded). Within warnings and errors, the issues are split into categories by ESLint rule name.
> 
> Example: ![image](https://user-images.githubusercontent.com/6326660/197923380-4c777e9b-8a8b-461b-8839-cde324be0a72.png)

Fix all errors under the category `jsx-a11y/alt-text`. _Please make sure to regression test so that we know nothing has broken through these changes._

List of issues (May not be exhaustive so double check):

- [ ] `wtt_front/client/src/pages/Tree/TreeMaintenanceDialog.js`
  - [ ]   56:13  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

**Comment by DamyanBG** [comment]
Please, assign me the issue.

**Comment by jazhen** [comment]
> Please, assign me the issue.

Assigned. Thank you!

**Comment by jazhen** [comment]
Closed by #351
