### ISSUE TITLE
[Planting Flow] Redesign Sign-In Screen

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#365]
Redesigning the sign in page to be more unique than the current design.

Tasks
- Clearly identify if Sign In or Sign Up. Currently the screens are the same or identical. The only difference is the tab saying sign in / wtt . 
- Give a more clear description of what is happening. Currently repeats wtt twice in the same sentence which makes sense, but not clear.
- design both desktop and mobile screens.

![Image](https://user-images.githubusercontent.com/98299952/204204436-1e6965e0-7f63-4fd4-9868-c315e87b9b3a.PNG)

**Comment by M1racle04** [comment]
Hii, would like to work on this

**Comment by ri0nardo** [comment]
@M1racle04 assigning you to the ticket. If you could show us the design that you create, we will give you feedback. Have fun with the ticket.

**Comment by ri0nardo** [comment]
@M1racle04 hows progress on this issue? any questions?

**Comment by keshao728** [comment]
Hey there! Is this still open? I would love to work on it. Also, I am new to GitHub Issues - where may I locate the Figma link (if there are any)?

**Comment by ri0nardo** [comment]
@keshao728 semms like @M1racle04 is assigned. @M1racle04 how is progress, its been about a month? Anything of note? There isn't a design as this is an extremely low priority ticket.

**Comment by ri0nardo** [comment]
@M1racle04 if there is another ticket that interest you please let us know!

**Comment by ri0nardo** [comment]
@keshao728 im assigning you this issue. There isn't a design that has been made, I recommend designing something before building it out.

**Comment by M1racle04** [comment]
Yes of course, just waiting for my paper to get over.

**Comment by keshao728** [comment]
Sounds good! I'll keep you posted on the design.

Thank you!

**Comment by ri0nardo** [comment]
@keshao728 how is progress on the sign-in screen?

**Comment by ri0nardo** [comment]
@keshao728 any updates?

**Comment by keshao728** [comment]
Hey Randy! Apologies just saw this.

I saw that we are powered by a third-party auth - Okta, therefore the
sign-in screen already seems to be working and done. I think the only to-do
here is to change the background of the page to a tree image that is usable.

bc Okta is a third-party app, the screen's design seems to be separated
from the code which I may not access (i could be wrong, please lmk!).
Perhaps the person who connected our app to Okta may have the access to
change the background?

**Comment by ri0nardo** [comment]
@keshao728 we will just close this ticket since its not something we want to deal with at this moment.
