### ISSUE TITLE
Better UI for tree detail action buttons

### ISSUE THREAD

**Issue by mwpark2014** [waterthetrees/wtt_front#409]
On desktop, users can hover over buttons in order to discern what buttons do.  However, that is harder if not impossible to do on mobile.

Would be great to alter the design of the buttons to include some text that'll make it more obvious what action buttons do on mobile.  Another option is to include a tutorial showing first-time users what each button does

![Image](https://user-images.githubusercontent.com/10445556/213076969-32288232-f6c0-41f8-8410-b1bd7b053530.png)

**Comment by 1san1** [comment]
hello i want to work on this issue

**Comment by ri0nardo** [comment]
@mwpark2014 theres a redesign that has yet to be implemented yet. #283

**Comment by mwpark2014** [comment]
@1san1 Looks like there are already designs ready for this. Feel free to make any comments on the design mocks in #283 . I can work with you to figure out how to start on this work

**Comment by ri0nardo** [comment]
@mwpark2014 since I redesigned the tree details do we want to keep this open?

**Comment by mwpark2014** [comment]
Thanks, closing this out!
