### ISSUE TITLE
[Epic - Survey / Feedback Feature] Feedback page to get user input

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#455]
***This is a documentation thread***

Have yet to deeply think about the best route for users to give feedback / their input on the app.

A few solutions I have thought of include:
1. Have a link to Github. (Have an area where users can fill out a form that can be reviewed and added as a ticket)
2. Use an outside service (google forms, Qualtrics) where users fill out a form and we get an email.
3. Have our own form that goes to the waterthetrees email.
4. Have a button where the map is. So users can immediately give us a bug report etc.

**Comment by Dawoodeveloper** [comment]
Can i solve this issue?
Please assign this issue to me. so i will contribute in this issue.

**Comment by ri0nardo** [comment]
#631 is the current ticket with this issue
