### ISSUE TITLE
[Planting Flow} Input Text Field Section Title Text needs more spacing from the input field above

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#465]
The input text field section title is one too small to read, and two is way too close to the input text field above it. Needs more spacing, padding per input text field. Also the gray color chosen for text is very difficult for me to read. Needs to be darker, but can still be gray.

![Image](https://user-images.githubusercontent.com/98299952/218298816-180d51a9-0618-4ce2-a89c-014c702b0ebd.PNG)

**Comment by hmzakhalid** [comment]
I'll fix it!. The text on the 
![image](https://user-images.githubusercontent.com/36852564/218299425-f3201c9f-5a76-4806-a18b-e92eb9ffef17.png)

**Comment by ri0nardo** [comment]
@hmzakhalid Cool I'll assign you to this issue. All the input text fields need to be revised. The issue is that the title leaks to the one above making it seem unrelated to the input field.

**Comment by Dawoodeveloper** [comment]
Can i solve this issue?
Please assign this issue to me. so i will contribute in this issue.

**Comment by hmzakhalid** [comment]
Hey @ri0nardo, I made a PR #472 
Please have a look and provide feedback!

**Comment by ri0nardo** [comment]
@hmzakhalid thanks for completing this ticket! Great work.
