### ISSUE TITLE
[Planting Flow - Design] Buttons are not clear on sidebar (Input Field)

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#466]
Buttons are very difficult to see or recognize on the sidebar. Either needs to be relocated or have an outline of a button. Having them as hyperlink buttons are not the appropriate button type for this scenario. 

Also the text for "Plant New Tree" should be reconsidered to something else. To me this meant to add another tree rather than confirm the information inputted for the tree.

![Image](https://user-images.githubusercontent.com/98299952/218298963-0666f8f2-98bf-4316-9fc8-6e5f0c37c90a.PNG)

**Comment by Dawoodeveloper** [comment]
Can i solve this issue?
Please assign this issue to me. so i will contribute in this issue.

**Comment by hmzakhalid** [comment]
I just quickly did some design changes in the chrome dev tools to get an idea.
What do you think? Should I start working on it?

![image](https://user-images.githubusercontent.com/36852564/218389477-4acbe36e-ad05-4038-b053-842c88ccf915.png)

**Comment by ri0nardo** [comment]
@hmzakhalid i would hold off for the time being. The whole design is still be planned out. But this is a good start for the buttons. We already have a design for a sidebar, but haven't integrated it for this menu.

**Comment by hmzakhalid** [comment]
Alrighty!

**Comment by ri0nardo** [comment]
@hmzakhalid i do have a question on how you got the horizontal green bar to move to the right. Since the sidebar isn't clipping it anymore.

**Comment by hmzakhalid** [comment]
@ri0nardo first set the `right: 0` in the `header.scss` then reducing the width will move the header to the right.
In practice we would make a GlobalContext that would set the header width as follow 
```js
import React, { useContext } from "react";
import { DrawerContext } from "./DrawerContext";

function Header() {
  const { open } = useContext(DrawerContext);

  return (
    <header style={{ width: open ? "calc(100% - 350px)" : "100%" }} className="header">
      <p>Header</p>
    </header>
  );
}

export default Header;
```

the `350px` is the drawer width.

**Comment by Dawoodeveloper** [comment]
Assign me any issue

**Comment by ri0nardo** [comment]
![Frame 162](https://user-images.githubusercontent.com/98299952/227106827-79db570b-c933-4e3a-b7e6-cdad371dfe27.jpg)
