### ISSUE TITLE
Redesigning the carbon section

### ISSUE THREAD

**Issue by mwpark2014** [waterthetrees/wtt_front#494]
Mocks are currently in the works

<img width="243" alt="carbon" src="https://user-images.githubusercontent.com/98299952/223327860-33d231e8-bac2-4f3d-996a-0ae5f3534f25.PNG">

**Comment by ri0nardo** [comment]
Added the c02 to the new tree details.
![All Tree Profile](https://user-images.githubusercontent.com/98299952/223329935-2bc3c9b0-71c9-4469-8e2f-332015470224.jpg)
