### ISSUE TITLE
Implement search bar UI component on mobile/desktop

### ISSUE THREAD

**Issue by mwpark2014** [waterthetrees/wtt_front#522]
Finalized mocks TBD but discussion here: https://github.com/waterthetrees/wtt_server/issues/120

https://www.figma.com/file/5C3v1LUNwMPQy9JOgnKEtr/Water-the-Trees?node-id=2700-20928

Mobile/desktop likely to have differences (mobile search results should take up whole screen with a dialog)

* Input field
* Autocomplete menu, which replaces input field text when result is selected
* Search results organized into categories
* Custom styled search result rows
* Keyboard shortcuts (Split up into separate github issue if not out of the box)
* Accessibility (Split up into separate github issue if not out of the box)

See MUI components

**Comment by mwpark2014** [comment]
@ri0nardo It looks like you removed the searchbar mock from the figma. Any chance you can add it back or link me to it elsewhere? It was a good visual to base my first iteration component on

**Comment by ri0nardo** [comment]
@mwpark2014 the design is still on figma, I just organized the file so everything is categorized. To find the design, go to the left side panel where pages are and click on "search / side menu design"
![Capture](https://user-images.githubusercontent.com/98299952/226091640-760b0113-3351-4ee5-b8e0-6e6e40d719b5.PNG)

**Comment by mwpark2014** [comment]
> @mwpark2014 the design is still on figma, I just organized the file so everything is categorized. To find the design, go to the left side panel where pages are and click on "search / side menu design" ![Capture](https://user-images.githubusercontent.com/98299952/226091640-760b0113-3351-4ee5-b8e0-6e6e40d719b5.PNG)

oh, my bad. that's awesome!
