### ISSUE TITLE
[Tree Details - Design] Mobile Tree Default Preview

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#540]
Forgot to design the mobile version of the tree details information section. I wanted to use the general section of the tree section with the tree species, section tabs, and adopt buttons as a preview.

I wanted to just recycle what I previously designed, but also wanted to explore other options to make the tabs be obvious that they are tabs. See below my iterations.
 
Here is the initial design. See #493 for sticky ticket.

![12-13 Pro - Default](https://user-images.githubusercontent.com/98299952/223248724-4b92d1c8-a17d-4590-a10d-05161acd3b5f.jpg)

**Comment by ri0nardo** [comment]
Started redesigning the top section of the tree details naming and section tabs. I always had an issue with the section tabs not be obvious to users. My solution was to make them be buttons so users could swipe to select other section tabs. From that I went with an outline and colored button that appears as a secondary button/badge.

From my findings the adopt and liked button were not obvious and wanted to give them a name tag along with an outline to make it a button. What are your thoughts on this redesign of the buttons? Also what do you think of a preview for trees you select on the screen? The idea is that a user would swipe up or press a section tab to pull up the trees full details. I see this as a benefit for the user experience since you aren't force into the tree details on mobile. You can ease yourself in rather than constantly going back to the map to find a different tree. @zoobot 

@mwpark2014 would this still work in the scope for the tree details container epic #433 ? 

![12-13 Pro - Section Button](https://user-images.githubusercontent.com/98299952/223251779-a580ea09-d4f3-4eff-b048-6e6ba9a48fde.jpg)
![12-13 Pro - New Adopt Button](https://user-images.githubusercontent.com/98299952/223251793-8fc75298-caf1-4da2-a4b8-e217cb1d90f9.jpg)
![12-13 Pro - Adopt Colored](https://user-images.githubusercontent.com/98299952/223251799-63b22736-2132-4c22-922a-5884639ad8c5.jpg)
![12-13 Pro - Both Changed](https://user-images.githubusercontent.com/98299952/223251807-1d82940e-95a2-44ce-af1e-c18516f0c033.jpg)

**Comment by ri0nardo** [comment]
Decided to make the liked and adopt buttons into radio buttons which will make it more fun. Also it will make the two actions more related to one another. 

I am now thinking if we need to make the adopt button disabled or locked when someone already adopted a tree. 

![12-13 Pro - Mobile Tree Details Adopt and Liked One Button](https://user-images.githubusercontent.com/98299952/223280038-e091bed4-0249-4453-b1f4-ee0e96262296.jpg)
![12-13 Pro - Mobile Tree Details Adopted Colored in](https://user-images.githubusercontent.com/98299952/223280041-c0cafcb7-a313-40a4-9697-8b8f4ddf607e.jpg)

**Comment by ri0nardo** [comment]
Increased the size of the section tabs to be larger and easier to see.

![12-13 Pro - Both Changed Added Margin](https://user-images.githubusercontent.com/98299952/223282889-10ddd37e-27f7-4eb0-8c0b-a2dd89be4873.jpg)

**Comment by mwpark2014** [comment]
> @mwpark2014 would this still work in the scope for the tree details container epic #433 ?

This looks like it's replacing the tabs in the mock? We should absolutely include it in #433. We don't have any tabs right now, right? We shouldn't spend time on implementing tabs in the near-future if we're going to be using buttons instead in the end. Will these changes reach desktop?

**Comment by ri0nardo** [comment]
> This looks like it's replacing the tabs in the mock? We should absolutely include it in #433. We don't have any tabs right now, right? We shouldn't spend time on implementing tabs in the near-future if we're going to be using buttons instead in the end. Will these changes reach desktop?
> 
> Probably would require redoing #483

The idea was that you would click the name to get to the specific section, but I always thought it wasn't as clear for people. That's the reason for the change for the tabs.
But this is a new additional step for viewing trees on mobile due to mobile not be optimized for a good user experience. So you would click a tree and this preview would appear with enough info for a person to either be interested or move on, and view the tree location at the same time.
This also changes the like and adopt buttons to now be radio buttons which I like more than what I previously did (not having labels was confusing for even me). The idea is similar to youtubes like system (but youtube removed the dislike number)

I would have to redo the desktop version, but its really just a copy and paste.

**Comment by mwpark2014** [comment]
Ahh, thanks for clarifying. I missed the whole point of this ticket, but I think I'm on the same page now. 

Hmm, I think this could be added to https://github.com/waterthetrees/wtt_front/issues/433, but it would need to be in a separate milestone. I don't think it would be too much work (hopefully, it can reuse the same base UI components), but I would want to prioritize it last compared to the main tree details component. 

I get why this is necessary for mobile - the tree details dialog takes up the entire screen! Previews would be very nice. I'd be very interested in what it'd look like in desktop or if it's even necessary for desktop tbh

**Comment by ri0nardo** [comment]
I see this as being more impactful, but implementation wise it would come after building out the the tree details. The current ux does not work on mobile. This only work optimally for desktop since you have enough screen real estate to have both the tree details and the map. 
The whole idea is to see the map and what tree you chose before you look more into the tree if you are interested.

**Comment by ri0nardo** [comment]
Added the address to the bottom sticky section. Will be more impactful in this container.
![12-13 Pro - Both Changed Added Margin](https://user-images.githubusercontent.com/98299952/223330532-9cb1f2a5-05fa-4216-a105-594bf3057f26.jpg)

**Comment by ri0nardo** [comment]
The first implementation will have no tabs as that wont be necessary for the first feature set.

![12-13 Pro - Both Changed Added Margin](https://user-images.githubusercontent.com/98299952/223331827-669f7642-9750-44c1-9de2-128e6cfcb718.jpg)
