### ISSUE TITLE
[Bug - Hamburger Menu] When hovering over a element you wont be redirected

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#630]
I was trying to redirect to another page on WTT, but noticed I wasn't being redirected even if I clicked the element. I noticed you have to click the text to be redirected. I tested it with all the elements in the hamburger menu and they all have the issue. Unless the text changes to the color blue it wont work.

![Image](https://user-images.githubusercontent.com/98299952/230513388-f5d92ac7-4606-4ce3-9ad4-3d77436c1a7b.gif)

**Comment by vladutvoicu** [comment]
Can I be assigned to this issue?

**Comment by ri0nardo** [comment]
> Can I be assigned to this issue?

assigning!

**Comment by majeediqbalsher** [comment]
if nobody working i am free

**Comment by bilalakhter** [comment]
if nobody working i am up for this

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me?
